### PR TITLE
Fix Button component onClick function

### PR DESCRIPTION
**Pull request by oneybee**

### CODE REVIEW

**Comment by ruucm** [comment]
@oneybee 

Please don't add `document.json` file on PR commits, cause it makes dirty conflicts

Resolve this conflict first on your local branch, and let me know

**Comment by oneybee** [comment]
merge master branch for resolve document.json file conflict

**Comment by oneybee** [comment]
delete other components changed code except for Button component

**Comment by ruucm** [comment]
@oneybee 

I merged it, but you didn't need to add `utils.js` and `document.json` file for this PR

**Pull request merged**
